@Coffee.Api_HostAddress = http://localhost:5100

### Get all coffees
GET {{ Coffee.Api_HostAddress }}/api/v1/coffee
Accept: application/json

### Get coffee by ID
GET {{ Coffee.Api_HostAddress }}/api/v1/coffee/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json

### Create new coffee
POST {{ Coffee.Api_HostAddress }}/api/v1/coffee
Content-Type: application/json

{
  "name": "Espresso"
}

### Update coffee
PUT {{ Coffee.Api_HostAddress }}/api/v1/coffee/3fa85f64-5717-4562-b3fc-2c963f66afa6
Content-Type: application/json

{
  "name": "Cappuccino"
}

### Delete coffee
DELETE {{ Coffee.Api_HostAddress }}/api/v1/coffee/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json

### Get coffees with pagination and search
GET {{ Coffee.Api_HostAddress }}/api/v1/coffee?page=1&pageSize=10&search=esp&sortBy=name&sortDescending=false
Accept: application/json

